apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-service-deployment
  namespace: default
  labels:
    app: react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
      - name: react-service
        image: victoriaperez/deploy-react-kubernetes
        ports:
        - containerPort: 8080


